server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
    gateway:
      routes:
        - id: customer
          uri: http://customer:8090
          predicates:
            - Path=/api/v1/customers/**
        - id: order
          uri: http://order:8070
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines
          uri: http://order:8070
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product
          uri: http://product:8050
          predicates:
            - Path=/api/v1/products/**
        - id: payment
          uri: http://payment:8060
          predicates:
            - Path=/api/v1/payments/**

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans