server:
  port: 8070
spring:
  application:
    name: order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-2:5432/order
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
application:
  config:
    customer-url: http://wrong_url
    payment-url: http://payment:8060/api/v1/payments
    product-url: http://product:8050/api/v1/products
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
resilience:
  feature: retryBackoff
  fallback-mocks:
    exampleFallback: '{"example": "example"}'
    findAllStudentsBySchool: '[{ "id": 1, "firstname": "John", "lastname": "Doe",
      "email": "john.doe@example.com", "schoolId": 1}]'
    purchaseProducts: '[{ "productId": 1, "name": "Wireless Headphones", "description":
      "High-quality wireless headphones with noise cancellation", "price": 199.99,
      "quantity": 2 }]'
