server:
  port: 8050
spring:
  application:
    name: product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-3:5432/product
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
chaos-engineering:
  wait: true
  duration: 40000
  kill-service: false
  return-500: false
  return-400: false
  return-429: false
